version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: vpn-check-tool-desktop-bakend
    environment:
      NODE_ENV: 'development'
      WEB_BACK_URL: ${WEB_BACK_URL}
    env_file:
      - .env
    expose:
      - '8081'
    ports:
      - '8081:8081'
    command: >
      bash -c "npm run start:${NODE_ENV}"
