version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: vpn-check-tool-desktop-bakend
    environment:
      NODE_ENV: ${NODE_ENV}
      WEB_BACK_URL: ${WEB_BACK_URL}
    env_file:
      - .env
    ports:
      - "8081:8081"
    command: npm run start:dev
