version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: vpn-check-tool-desktop-bakend
    environment:
      NODE_ENV: dev
      WEB_BACK_URL: ${WEB_BACK_URL}
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:${NODE_ENV}
    ports:
      - "8081:8081"
